import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Result from '../components/Result'
import requests, { API_KEY } from '../utils/requests'


export default function Home(props) {
 console.log(props)
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Result /> 
    </div>
  )
};

export async function getServerSideProps(context) {

  const genre  = context.query.genre
  console.log('brni')

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTv.url
    }`)
  .then(res=> res.json());
  console.log(request)
 
  
  return {
    props: {...request.results}
  }

}
